### PR TITLE
added new colors for light and dark mode

### PR DESCRIPTION
**Pull request by leske42**
So i have made new beautiful colors for dark mode & like this light mode is black again. it is approved by Lukas & Arthur. also i put the color definition for the note thing in the css file so its easier to edit if you want to change it.

### CODE REVIEW

**Comment by leske42** [comment]
run-prettier

**Comment by leske42** [comment]
image
This is dark mode color & light mode button is just black

**Comment by itislu** [comment]
I like it!

**Review by itislu — APPROVED** [review]

**Comment by leske42** [comment]
image
This is normal light mode

**Review by ifaoji — APPROVED** [review]

**Pull request merged**
