### PR TITLE
feat(front): add buttons to sort issues

### PR DESCRIPTION
**Pull request by itislu**
- **Sort by creation date as secondary criterion by default.**
  Motivation: As soon as there would be multiple issues, new issues will be completely at the bottom, so it would get hard to find them. Also, more recent issues with the same amount of upvotes as older issues might be more important, bc they got to that number in less time.

- **Add buttons to sort issues.**
  Sort by upvotes or creation date, descending or ascending.

- **Store the current sort selection.**
  Keep the selection even when navigating through the issues and the whole site by using localStorage.
> [!IMPORTANT]
> **NEED HELP**
> - [X] There's still a bug introduced with f37f864: When on the Issues page and reloading with F5, an error occurs.
> - [x] Bug with Arthur's commit 296562b: On first click on a column, it should sort descending. Now it is ascending.

### CODE REVIEW

**Comment by winstonallo** [comment]
@ifaoji are you doing this or do you need me to take care of it?

**Comment by winstonallo** [comment]
Okay so I think the problem is that localStorage is a browser API, and is therefore not available during the server-side-rendering process in Remix (the server-side code gets executed first).

**Comment by winstonallo** [comment]
@itislu I pushed a potential fix, can you lmk if it works for you?

**Comment by winstonallo** [comment]
Also simon refactored the whole directory structure with his last PR, when you're ready can you pls make a new PR branching out of main pls?

**Comment by itislu** [comment]
> I pushed a potential fix, can you lmk if it works for you?

There's no reload problem anymore, nice!
However, the behavior has been changed when clicking on a column to sort.
On first click , it should sort descending. Now it is ascending.

**Comment by itislu** [comment]
> Also simon refactored the whole directory structure with his last PR, when you're ready can you pls make a new PR branching out of main pls?

Ok I rebased it onto the new main. It was the easiest way to deal with the conflicts.

**Comment by winstonallo** [comment]
@itislu should be good now

**Comment by itislu** [comment]
Yup the order and symbols make sense now.
The only problem remaining is that when you go to the Issues page the first time, there's no symbol next to the column names.

**Review by winstonallo — APPROVED** [review]
lgtm

**Pull request merged**
