### PR TITLE
fix(front): Update anonymity warnings

### PR DESCRIPTION
**Pull request by itislu**
@ifaoji Why do the bullet points not work? Is it bc it can only be strings?

### CODE REVIEW

**Comment by ifaoji** [comment]
For the list you need to add a [style type](https://tailwindcss.com/docs/list-style-type). In this case `list-disc`.
Example to make it look better (from shadcn/ui):
```tsx
export function TypographyList() {
  return (
    <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
      <li>1st level of puns: 5 gold coins</li>
      <li>2nd level of jokes: 10 gold coins</li>
      <li>3rd level of one-liners : 20 gold coins</li>
    </ul>
  )
}
```

**Comment by ifaoji** [comment]
Oh, and while you're at it, could you also remove the `Currently you are not able to edit issues after submitting them.` part? This will not be possible anymore.

**Comment by itislu** [comment]
> Oh, and while you're at it, could you also remove the Currently you are not able to edit issues after submitting them. part? This will not be possible anymore.

I thought of it, but wouldn't it be possible in the current session?
Ofc, next time you log in it's not possible anymore. But straight after posting it?

**Comment by ifaoji** [comment]
No, issues are currently not bound to sessions. Also idk whether it would be a good idea to do that :thinking:

**Comment by itislu** [comment]
Yeah you're right it's probably not a good idea to make them editable, considering that some people might have already upvoted it.

**Comment by itislu** [comment]
@ifaoji Please help 😭
I want to create an info box above or next to the Upvote button, but I just cannot get it to work...
This would be the text inside the info box:
```
To ensure every student can only vote once, each vote gets stored with the user ID in a database, making votes not fully anonymous to the student council.
```

**Review by ifaoji — APPROVED** [review]

**Pull request merged**
