### PR TITLE
ci: trigger Prettier with write access in PR comment or with manual run

### PR DESCRIPTION
**Pull request by itislu**
Prettier with write access will run and push to the branch when...
- ~requesting a Pull Request review~
- commenting with `run-prettier` on a Pull Request
- triggered manually for a branch in the Actions -> Prettier Format Write -> Select branch

### CODE REVIEW

**Comment by ifaoji** [comment]
That's nice, one problem I can see though is: It automatically writes to the branch. People who don't use prettier / format later will experience merge conflicts if they want to change code after pushing.

**Comment by itislu** [comment]
Oh that's true. I don't have Prettier installed myself, that's why I thought it's convenient.
But I can just make it a workflow on dispatch, so it has to be triggered manually.

**Comment by winstonallo** [comment]
I don't know if I'm a fan of changing code on remote tbh. Why do you not want to install Prettier?

**Comment by itislu** [comment]
@winstonallo I guess you're right, there's not much reason why I didn't. I did it now.
But it raises the barrier to contribute a bit imo, just bc you have to set up your environment.
Having it be done automatically might be quite convenient for casual contributors.

If you prefer, I can change it so that it can only be triggered manually?
At the moment it happens both when requesting a pull request review, and when triggering the workflow manually.

**Comment by winstonallo** [comment]
> @winstonallo I guess you're right, there's not much reason why I didn't. I did it now. But it raises the barrier to contribute a bit imo, just bc you have to set up your environment. Having it be done automatically might be quite convenient for casual contributors.
> 
> If you prefer, I can change it so that it can only be triggered manually? At the moment it happens both when requesting a pull request review, and when triggering the workflow manually.

Sounds good:)

**Comment by ifaoji** [comment]
I'd prefer to not format it automatically if a review is requested. Instead it would be nice to have a command like `run-prettier` which we can just send as a comment, and then the workflow gets triggered for PRs.

**Comment by itislu** [comment]
Yup that would be cool. I'll look into that.

**Comment by itislu** [comment]
run-prettier

**Comment by itislu** [comment]
Well at least that's how it's going to work once the workflow file is on the main branch... 🙄

- You can see how it will look like in my test repo here: https://github.com/itislu/GitHub-Actions/pull/1

**Pull request merged**
