### PR TITLE
feat(front): make all buttons reactive to length limits

### PR DESCRIPTION
**Pull request by itislu**
- Make all buttons reactive to text length limits.
- Use global constants for length limits.
- Fix the selection button hint overlaying other buttons on the contact page.

### CODE REVIEW

**Comment by itislu** [comment]
run-prettier

**Review by ifaoji — CHANGES_REQUESTED** [review]
If we go this route, then I would also like to have error messages which are shown when something is wrong.

For example:
First time user: I have an issue and such a good title, that I think that I don't need a description. Why can I not press the button?

Previously it showed what is wrong, giving instant feedback.

**Comment by itislu** [comment]
That's a good point.

Continuing your example, maybe we should allow posts without descriptions too?

**Comment by ifaoji** [comment]
I don't think we should allow posts with no description. The title should be a quick introduction into the topic and then the description should explain it in more detail.

**Comment by itislu** [comment]
> I don't think we should allow posts with no description. The title should be a quick introduction into the topic and then the description should explain it in more detail.

Ok
---
> If we go this route, then I would also like to have error messages which are shown when something is wrong.

How about that the color of the button looks like it is disabled, but it is still clickable so that if you click on it the error messages and hints will pop up?

**Comment by ifaoji** [comment]
I'd find that a bit confusing :thinking:

**Comment by itislu** [comment]
> I'd find that a bit confusing 🤔

@ifaoji Could you check how you like it when creating a new issue?

If you do like it, could you help me to also create these error popups (schemas) for the other text boxes?

**Comment by itislu** [comment]
### Still having 3 bugs:
- [ ] The comment button in the detailed issue page sometimes has to be pressed twice to get the error popups or even to submit a valid text box.
- [ ] For any text box, when refreshing the page with an invalid text box, atm sth has to be typed again in order for the popups to work again.
- [ ] On the contact page, the popup for the selection buttons appears in a very bad bad position:
image

**Comment by itislu** [comment]
Fixed the selection button hint overlaying other buttons like this: 
image

**Comment by itislu** [comment]
run-prettier

**Pull request merged**
