### PR TITLE
feat: apply `open` and `archived` tags on Discord

### PR DESCRIPTION
**Pull request by itislu**
It doesn't work yet...

### CODE REVIEW

**Comment by itislu** [comment]
@ifaoji If you have time can you take a look please?

**Comment by itislu** [comment]
It needs a message to be sent.
Todo: 
- [ ] Send a message like "This issue was archived." on Discord and it applies the tag too.

**Comment by itislu** [comment]
The previous comment is actually not true.
The issue was bc of not using the tag ids. Using the tag ids applies the open tag when a new issue gets created correctly.
However, changing the tags when archiving or unarchiving does not work with the current implementation.

**Comment by leeoocca** [comment]
What's the biggest blocker for this one? Just the conflicts?

**Comment by leeoocca** [comment]
I tested this again and I don't think it's possible to change tags with a webhook call... I think it's not properly documented but the API only allows assignation at creation.

> If in a forum/media channel and creating a new thread (see thread_name above), the tags to apply to the new thread.
> https://docs.disnake.dev/en/latest/api/webhooks.html

I found the hint above in some library's docs. The official docs are ambiguous about it, and the behavior didn't work for me locally.

> array of tag ids to apply to the thread (requires the webhook channel to be a forum or media channel)
> https://discord.com/developers/docs/resources/webhook#execute-webhook

My biggest question atm is... 😅 how is it working in production without the tag snowflakes (ids)? It doesn't work for me locally... It doesn't even accept the webhook:

```
rawError: {
     message: 'Invalid Form Body',
     code: 50035,
     errors: { applied_tags: [Object] }
   },
```

**Comment by leeoocca** [comment]
I didn't even find the `applied_tags` mention in the current code: https://github.com/42-student-council/website/blob/main/src/app/routes/_app.issues.new.tsx#L100

Is someone adding the tags manually every time? 😅

**Comment by itislu** [comment]
> Is someone adding the tags manually every time?

Yup, I always did it 😅

**Comment by leeoocca** [comment]
I'm pretty sure we can't do this... Might be good to close this and #172.

I don't think it's possible to implement it with a webhook.

**Pull request closed without merging**
