### PR TITLE
fix: bottleneck 42 api requests

### PR DESCRIPTION
**Pull request by ifaoji**

### CODE REVIEW

**Review by winstonallo — APPROVED** [review]
lgtm

**Comment by itislu** [comment]
@ifaoji What does this actually do, how does it work? Kamilla and me are curious.

**Comment by ifaoji** [comment]
I just chose the simple route which is: Allow one request to be made every `1000 / REQUEST LIMIT` milliseconds.

**Comment by itislu** [comment]
And so otherwise you wait in a queue?

**Comment by ifaoji** [comment]
yes

**Pull request merged**
