### PR TITLE
improve: move votes column to the left

### PR DESCRIPTION
**Pull request by itislu**
Having the votes and comments next to each other looks weird.

Leo also suggested to move the votes more to the left.

image

### CODE REVIEW

**Comment by ifaoji** [comment]
Would it be possible to move the votes and the title closer together :thinking: 
I think it could look better.

**Comment by itislu** [comment]
@ifaoji Yes we thought the same, but we don't know how

**Comment by itislu** [comment]
@ifaoji Looks like you will have to make a new PR then 😁

**Comment by itislu** [comment]
Oh and I worry how the phone looks like now. You won't see much of the title...

**Pull request merged**
