### PR TITLE
improve: back button on IssueDetail leads to same-state list

### PR DESCRIPTION
**Pull request by leeoocca**
Might be a simpler improvement implementation for https://github.com/42-student-council/website/pull/129
Might close https://github.com/42-student-council/website/issues/158

### CODE REVIEW

**Comment by itislu** [comment]
This does not seem to work for me...

**Comment by leeoocca** [comment]
> not really a fix, just a UX improvement

Good point, I updated the description.

> This does not seem to work for me...

Which part exactly? It won't save it after you go out of the issue list page, just at least it links to the list of same-state issues. More limited in scope but still an improvement.

**Comment by itislu** [comment]
> Which part exactly?

The `Open/Archived issues` button.
It still always goes back to the open issues, no matter if coming from the archived issues list.

Please someone else test it too, maybe Kamilla and me were just stupid.

**Comment by leeoocca** [comment]
> It still always goes back to the open issues, no matter if coming from the archived issues list.

Oh yeah, I messed up big time after I created a component to keep the label logic together. Lesson learned: triple check before committing even if it worked until 1 min ago 😅 It's never too late to mess up.

The props were not passed correctly. I also took the chance to minimize the data passed to the essentials.

Now it should work as expected.

**Review by itislu — APPROVED** [review]
Yup now it works 😁
Now worries, that's what code review is for!

**Comment by itislu** [comment]
@leeoocca @ifaoji Wait what happened, on the live site there is still the "Go Back" button which always leads to the open issues.

**Comment by leeoocca** [comment]
Yup, confirmed, it was overwritten by #189 

https://github.com/42-student-council/website/blame/65b9e12a5154abcb8d9c1d875d556ca8add832d5/src/app/routes/_app.issues.%24id.tsx#L397

**Comment by itislu** [comment]
Yup it's fixed now, thank you!!

**Pull request merged**
