### PR TITLE
FIX: hasVoted state

### PR DESCRIPTION
**Pull request by winstonallo**
Add: 
* Now track the vote state of the current session to change the button color accordingly

**hasVoted == false:**
image

**hasVoted == true:**
image

Also removed these ugly ass popups

### CODE REVIEW

**Comment by itislu** [comment]
The red is quite scary.
Is it possible to change it to the same color as the "Made with love"? It's **#f43f5e**
image

**Comment by itislu** [comment]
As for the not-yet-voted state, to make it more consistent maybe use the same color as for the Submit button once there's something in the text field:
No-hover: 
image


Hover:
image

**Comment by winstonallo** [comment]
Okay, i won't have time to do it until lter to ight tho

**Comment by winstonallo** [comment]
@itislu alr should be good now, lmk and ill merge

**Comment by itislu** [comment]
Sorry for the late reply.
Yup it's great!

**Pull request merged**
