### PR TITLE
refactor: make issue list buttons look better on mobile

### PR DESCRIPTION
**Pull request by ifaoji**
image

Also removes the `I also have something to say!` text on desktop for consistency.

### CODE REVIEW

**Comment by itislu** [comment]
Kamilla and I don't really like this

**Comment by ifaoji** [comment]
It's better UX on mobile though. What exactly do you not like?

**Comment by itislu** [comment]
The button feels just too big.
And separating the tab toggle and the button into 2 lines takes up more vertical space until you reach the actual important part of the page - the issues.

On desktop we like the `I also have something to say!`. It gives the site some flavour, so it's not so bland.

**Comment by ifaoji** [comment]
Can you take a look at how it looks like on the phone? Sometimes the desktop makes it look bigger than it actually is. Imo the size is fine.

**Comment by itislu** [comment]
And what about the vertical size? It wastes a whole issue row of space

**Comment by ifaoji** [comment]
It's not that drastic since we don't have such a huge amount of issues open at the same time you can still see pretty much everything.

**Comment by leske42** [comment]
But we worked so much on current version i think it's perfect

**Comment by ifaoji** [comment]
No the current version was thrown together quickly

**Comment by leske42** [comment]
Not even true we used all our knowledge

**Comment by ifaoji** [comment]
Suuuuuure

**Comment by ifaoji** [comment]
This page was thrown together in like 10 minutes :laughing:

**Comment by leske42** [comment]
Hey if you want contributors don't talk shit about their contributions especially after merging them

**Comment by ifaoji** [comment]
This page was created by us during a meeting. It was the best solution back then because we needed it quickly, but this does not mean that we need to stick to this solution all the time. We can still improve it.

**Comment by itislu** [comment]
That is true, the reason to not merge it should not be the effort we spent on it. 
We can just vote on discord what we prefer.

**Comment by itislu** [comment]
But the `I also have something to say!` button on desktop should really stay...

**Comment by ifaoji** [comment]
Since I like consistency (not displaying different content on different screens) it should be the same text.
Since the mobile button is bigger now it can also show the text `I also have something to say!`.
So both mobile and desktop can show the fancy text.

**Comment by itislu** [comment]
image

**Pull request closed without merging**
