### PR TITLE
improve(front): display date and time of issue comments

### PR DESCRIPTION
**Pull request by itislu**
- Also use user's locale for issue time format instead of hardcoded en-GB.

### CODE REVIEW

**Comment by itislu** [comment]
- Leaving the format issues so we can test if #96 works once merged :)

**Comment by itislu** [comment]
Oh sorry I should have been more clear, this one should not have been merged yet since we'd need to comment `run-prettier` here 😳

**Comment by winstonallo** [comment]
oops mb

**Comment by itislu** [comment]
run-prettier
Just to get rid of the ❌

**Pull request merged**
