### PR TITLE
improve: remember archived tab state when navigating back to issues list

### PR DESCRIPTION
**Pull request by itislu**
## TODO
- [ ] Clicking on issues when already in the archived tab on the issues page should go back to the online tab.
- [ ] After having created a new issue, the tab state should be set to the online tab.
- [ ] When being on the archived tab, it should add a parameter to the URL so that the state is sharable.

### CODE REVIEW

**Comment by itislu** [comment]
run-prettier

**Comment by itislu** [comment]
run-prettier

**Comment by winstonallo** [comment]
Is it intended to work only for issue list <-> issue page? When I go to home while on archived mode, the list is back in online mode when I get back

**Comment by itislu** [comment]
Back then I thought it was better this way. But now that you say it and I tested it again, it feels weird.
I will change it so the state stays, no matter where you go on the site.

Also if you click on Issues while already being in the archived issues, it also goes back to the online tab. That I like though.

**Pull request closed without merging**
